import { Router } from 'express';
import { calculateBooking, cancelBooking, createBooking, myBookings, ownerBookings, ownerDecision, payBooking } from '../controllers/bookingController.js';
import { authorize, protect } from '../middleware/auth.js';
const router = Router();
router.use(protect);
router.post('/calculate', authorize('user'), calculateBooking);
router.post('/', authorize('user'), createBooking);
router.get('/mine', authorize('user'), myBookings);
router.patch('/:id/cancel', authorize('user'), cancelBooking);
router.get('/owner', authorize('owner'), ownerBookings);
router.patch('/:id/decision', authorize('owner'), ownerDecision);
router.post('/:id/pay', authorize('user'), payBooking);
export default router;
