import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../api';
import FarmhouseCard from '../components/FarmhouseCard';
export default function Home(){const [farms,setFarms]=useState([]);useEffect(()=>{api.get('/farmhouses').then(r=>setFarms(r.data.farmhouses.slice(0,3))).catch(()=>{});},[]);return <>
<section className="hero"><div className="hero-glow"/><div className="container hero-inner"><div className="row align-items-center"><div className="col-lg-8"><div className="eyebrow"><span className="pulse-dot"/> curated countryside stays</div><h1>Escape the ordinary.<br/><span>Stay somewhere alive.</span></h1><p>Handpicked farmhouses with private pools, open lawns and slow mornings. Discover your next weekend story.</p><Link to="/farmhouses" className="btn btn-primary-custom btn-lg rounded-pill px-4 me-2">Explore stays <i className="bi bi-arrow-up-right ms-1"/></Link><Link to="/register" className="btn btn-glass btn-lg rounded-pill px-4">Become a host</Link></div></div><div className="hero-stats"><div><strong>120+</strong><span>curated stays</span></div><div><strong>4.8/5</strong><span>guest rating</span></div><div><strong>24/7</strong><span>support</span></div></div></div></section>
<section className="search-strip"><div className="container"><div className="search-box row g-2 align-items-end"><div className="col-lg-5"><label>Where</label><div className="input-wrap"><i className="bi bi-geo-alt"/><input id="homeSearch" className="form-control" placeholder="City, valley or farmhouse"/></div></div><div className="col-lg-3"><label>Guests</label><div className="input-wrap"><i className="bi bi-people"/><input className="form-control" type="number" min="1" defaultValue="2"/></div></div><div className="col-lg-4"><Link to="/farmhouses" className="btn btn-dark w-100 py-3 rounded-3">Search available stays <i className="bi bi-search ms-2"/></Link></div></div></div></section>
<section className="section-pad" id="why-us"><div className="container"><div className="section-head"><div><span className="section-kicker">why FarmNest</span><h2>Designed for better escapes.</h2></div><p>Every stay is presented with clear pricing, thoughtful details and a simple request-to-confirm booking flow.</p></div><div className="row g-4"><Feature icon="shield-check" title="Approval-first trust" text="Owner listings are reviewed by admin before they become visible."/><Feature icon="calendar2-check" title="Human confirmation" text="Your booking is a request first. The owner confirms it before payment."/><Feature icon="stars" title="Real stay reviews" text="Reviews unlock only after a confirmed, paid booking."/></div></div></section>
<section className="section-pad section-dark"><div className="container"><div className="section-head light"><div><span className="section-kicker">featured stays</span><h2>Places worth slowing down for.</h2></div><Link to="/farmhouses" className="btn btn-outline-light rounded-pill px-4">View all</Link></div><div className="row g-4">{farms.map(f=><div className="col-md-6 col-lg-4" key={f._id}><FarmhouseCard farmhouse={f}/></div>)}</div></div></section>
<section className="section-pad"><div className="container"><div className="host-banner"><div><span className="section-kicker">for owners</span><h2>Turn your farmhouse into a destination.</h2><p>Submit your property, let our admin review it, then start receiving booking requests.</p></div><Link to="/register" className="btn btn-dark rounded-pill px-4">List my farmhouse <i className="bi bi-arrow-up-right ms-1"/></Link></div></div></section></>}
function Feature({icon,title,text}){return <div className="col-md-4"><div className="feature-card h-100"><div className="feature-icon"><i className={`bi bi-${icon}`}/></div><h5>{title}</h5><p>{text}</p></div></div>}
