import { Router } from 'express';
import { availability, createFarmhouse, deleteFarmhouse, getFarmhouse, listFarmhouses, ownerFarmhouses, toggleFarmhouseStatus, updateAvailability, updateFarmhouse } from '../controllers/farmhouseController.js';
import { authorize, protect } from '../middleware/auth.js';
const router = Router();
router.get('/', listFarmhouses);
router.get('/owner/mine', protect, authorize('owner'), ownerFarmhouses);
router.get('/:id/availability', availability);
router.get('/:id', getFarmhouse);
router.post('/', protect, authorize('owner'), createFarmhouse);
router.put('/:id', protect, authorize('owner'), updateFarmhouse);
router.patch('/:id/status', protect, authorize('owner'), toggleFarmhouseStatus);
router.put('/:id/availability', protect, authorize('owner'), updateAvailability);
router.delete('/:id', protect, authorize('owner'), deleteFarmhouse);
export default router;
