import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function Register() {
  const { register } = useAuth(); const navigate = useNavigate();
  const [form, setForm] = useState({ name: '', email: '', phone: '', password: '', role: 'user' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); setBusy(true); try { const user = await register(form); navigate(user.role === 'owner' ? '/owner' : '/dashboard'); } catch (err) { setError(err.response?.data?.message || 'Registration failed.'); } finally { setBusy(false); } };
  return <section className="auth-page"><div className="auth-overlay" /><div className="container position-relative"><div className="row justify-content-center"><div className="col-md-7 col-lg-5"><div className="auth-card bg-white rounded-4 shadow-lg p-4 p-lg-5"><Link to="/" className="text-decoration-none text-dark d-flex justify-content-center align-items-center gap-2 fw-bold fs-5"><span className="brand-mark"><i className="bi bi-house-heart-fill" /></span>FarmHouse<span className="brand-accent">Rent</span></Link><h2 className="fw-bold text-center mt-4 mb-2">Create your account</h2><p className="text-secondary text-center mb-4">Start booking or list your farmhouse.</p>{error && <div className="alert alert-danger">{error}</div>}<form onSubmit={submit}><label className="form-label">Full Name</label><input required className="form-control mb-3" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><label className="form-label">Email</label><input required type="email" className="form-control mb-3" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><label className="form-label">Phone</label><input className="form-control mb-3" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><label className="form-label">Account Type</label><select className="form-select mb-3" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="user">Customer</option><option value="owner">Property Owner</option></select><label className="form-label">Password</label><input required minLength="6" type="password" className="form-control mb-4" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button disabled={busy} className="btn btn-success w-100 rounded-pill py-3">{busy ? 'Creating account...' : 'Create Account'}</button><p className="text-center text-secondary small mt-4 mb-0">Already have an account? <Link className="text-success fw-semibold" to="/login">Login</Link></p></form></div></div></div></div></section>;
}
